apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
        - name: mywebapp-container
          image: ferhatchibane/jenkins_test:latest # Pull from private Docker Hub repository
          imagePullPolicy: Always # Always pull the latest image
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  selector:
    app: mywebapp # This must match the label in the deployment
  ports:
    - protocol: TCP
      port: 80    # Exposes the app on port 80 externally
      targetPort: 80    # Forward traffic to port 80 in the container
      nodePort: 30080  # Expose the service on a NodePort (you can choose a port between 30000-32767)
  type: NodePort  # Exposes the service outside the cluster via the node's IP and the NodePort
