apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
        - name: mywebapp-container
          image: ferhatchibane/jenkins_test:latest # Pull from private Docker Hub repository
          imagePullPolicy: Always # Always pull the latest image
          ports:
            - containerPort: 80
